---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: acme-app-composition
spec:
  compositeTypeRef:
    apiVersion: acme.com/v1alpha1
    kind: AcmeApp
  resources:
    - name: helm-release
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: "{{ .spec.appName }}"
        spec:
          forProvider:
            chart:
              name: acme-app
              repository: https://gitops-ci-cd.github.io/helm-charts/
              version: "0.2.2"
            values:
              replicaCount: "{{ .spec.replicas }}"
            namespace: ""
          providerConfigRef:
            name: helm-provider
      patches:
        - fromFieldPath: spec.namespace
          toFieldPath: metadata.namespace
        - fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace
