---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: acmeapps.acme.com
spec:
  group: acme.com
  names:
    kind: AcmeApp
    plural: acmeapps
  claimNames:
    kind: AcmeAppClaim
    plural: acmeappclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                  description: Namespace where resources will be created.
                  default: default
                appName:
                  type: string
                  description: Name of the application.
                replicas:
                  type: integer
                  description: Number of replicas.
                  default: 1
              required:
                - appName
      defaultCompositionRef:
        name: acme-app-composition
