---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: acmeapps.acme.com
spec:
  group: acme.com
  names:
    kind: AcmeApp
    plural: acmeapps
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
              properties:
                namespace:
                  type: string
                  description: The namespace in which resources will be created.
            spec:
              type: object
              properties:
                appName:
                  type: string
                  description: Name of the application.
                replicas:
                  type: integer
                  description: Number of replicas.
              required:
                - appName
      defaultCompositionRef:
        name: acme-app-composition
